# ohmyzsh-like git aliases
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit --verbose'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git pull'
alias glog='git log --oneline --decorate --graph'
alias glg='git log --stat'
alias gp='git push'
alias gpd='git push --dry-run'
alias gst='git status'
alias gss='git status --short'
alias gsw='git switch'
