source ~/dotfiles/.vim/minimal.vim

set foldmethod=marker
set foldcolumn=1

" Plugins {{{
packadd comment
" }}}

if filereadable(expand('~/dotfiles/.vim/local.vim'))
    source ~/dotfiles/.vim/local.vim
endif
